import { CreateAnnonceInputs } from "../../models/Inputs/FormType";

export const textsInputsCreateAnnonce: CreateAnnonceInputs = {
  title: {
    title: "Titre",
    label: "Titre",
    id: "title",
    type: "text",
    name: "title",
    helperText: "Veuillez entrer le titre de l'annonce",
    placeholder: " Peugeot 208 1.6 5P",
    size: "small",
    required: true,
    afterFocus: "Entrez le titre de l'annonce",
  },
  price: {
    title: "Prix",
    label: "Prix",
    id: "price",
    type: "text",
    name: "price",
    helperText: "Veuillez entrer le prix ex : 10000 €",
    placeholder: " 10000 €",
    size: "small",
    required: true,
    afterFocus: "Entrez le prix de l'annonce",
  },
  transaction: {
    title: "Transaction",
    label: "Transaction",
    id: "transaction",
    type: "text",
    name: "transaction",
    helperText: "Veuillez sélectionner le type de transaction",
    placeholder: "Sélectionner le type de transaction",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez le type de transaction",
  },
  quantity: {
    title: "Quantité",
    label: "Quantité",
    id: "quantity",
    type: "number",
    name: "quantity",
    helperText: "Veuillez entrer la quantité ex : 1",
    placeholder: " 1",
    size: "small",
    required: true,
    afterFocus: "Entrez la quantité",
  },
  city: {
    title: "Ville",
    label: "Ville",
    id: "city",
    type: "text",
    name: "city",
    helperText: "Veuillez entrer la ville ex : Casablanca",
    placeholder: " Casablanca",
    size: "small",
    required: true,
    afterFocus: "Entrez la ville",
  },
  phoneNumber: {
    title: "Numéro de téléphone",
    label: "Numéro de téléphone",
    id: "phoneNumber",
    type: "text",
    name: "phoneNumber",
    helperText: "Veuillez entrer le numéro de téléphone ex : 06 00 00 00 00",
    placeholder: " 06 00 00 00 00",
    size: "small",
    required: true,
    afterFocus: "Entrez le numéro de téléphone",
  },

  type: {
    title: "Type",
    label: "Type",
    id: "type",
    type: "text",
    name: "type",
    helperText: "Veuillez sélectionner le type de véhicule",
    placeholder: " Sélectionner le type de véhicule",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez le type de véhicule",
  },
  mark: {
    title: "Marque",
    label: "Marque",
    id: "mark",
    type: "text",
    name: "mark",
    helperText: "Veuillez sélectionner la marque du véhicule",
    placeholder: " Sélectionner la marque du véhicule",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez la marque du véhicule",
  },
  model: {
    title: "Modèle",
    label: "Modèle",
    id: "model",
    type: "text",
    name: "model",
    helperText: "Veuillez sélectionner le modèle du véhicule",
    placeholder: " Sélectionner le modèle du véhicule",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez le modèle du véhicule",
  },
  year: {
    title: "Année",
    label: "Année",
    id: "year",
    type: "number",
    name: "year",
    helperText: "Veuillez entrer l'année du véhicule ex : 2024",
    placeholder: " 2024",
    size: "small",
    required: true,
    afterFocus: "Entrez l'année du véhicule",
  },
  gearbox: {
    title: "Boîte de vitesses",
    label: "Boîte de vitesses",
    id: "gearbox",
    type: "text",
    name: "gearbox",
    helperText: "Veuillez sélectionner la boîte de vitesses",
    placeholder: " Sélectionner la boîte de vitesses",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez la boîte de vitesses",
  },
  climatisation: {
    title: "Climatisation",
    label: "Climatisation",
    id: "climatisation",
    type: "text",
    name: "climatisation",
    helperText: "Veuillez sélectionner la climatisation du véhicule",
    placeholder: " Sélectionner la climatisation du véhicule",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez la climatisation du véhicule",
  },
  condition: {
    title: "État",
    label: "État",
    id: "condition",
    type: "text",
    name: "condition",
    helperText: "Veuillez sélectionner l'état du véhicule",
    placeholder: " Sélectionner l'état du véhicule",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez l'état du véhicule",
  },
  fuelType: {
    title: "Type de carburant",
    label: "Type de carburant",
    id: "fuelType",
    type: "text",
    name: "fuelType",
    helperText: "Veuillez sélectionner le type de carburant du véhicule",
    placeholder: " Sélectionner le type de carburant du véhicule",
    size: "small",
    required: true,
    afterFocus: "Sélectionnez le type de carburant du véhicule",
  },
  klm_counter: {
    title: "Compteur kilométrique",
    label: "Compteur kilométrique",
    id: "klm_counter",
    type: "text",
    name: "klm_counter",
    helperText:
      "Veuillez entrer le compteur kilométrique du véhicule ex : 100000 km",
    placeholder: " 100000 km",
    size: "small",
    required: true,
    afterFocus: "Entrez le compteur kilométrique du véhicule",
  },

  description: {
    title: "Description",
    label: "Description",
    id: "description",
    type: "text",
    name: "description",
    helperText: "Veuillez entrer la description du véhicule",
    placeholder:
      " Peugeot 208 1.6 5P, Occasionnel, 100000 km, Climatisation, Essence",
    size: "small",
    required: true,
    afterFocus: "Entrez la description du véhicule",
  },

  images: {
    title: "Images",
    label: "Images",
    id: "images",
    type: "file",
    size: "small",
    required: true,
    afterFocus: "Entrez les images de l'annonce",
    name: "images",
    helperText: "Veuillez entrer les images du véhicule",
  },
};
